### PR TITLE
FIX: Fixes #13 Permits interpolated constants in YML config.

### LINKED ISSUE #13: Allow env-derived constants in YML config
If I want to take an S3 bucket host from an environment variable, I should be able to surround it with backticks in YML and the module should interpolate it correctly. 

To acheive this, `Extensons/ControllerCSPExtension` needs to be patched with a call to `Injector::convertServiceProperty()` as follows:

Example YML:

```yml
...
    img-src:
      allow:
        - '`AWS_BUCKET_NAME`'
      blob: false
      self: true
      data: true
...
```

Patched logic:

```php
...
    public function onAfterInit()
    {
        /** @var Controller $owner */
        $owner = $this->owner;
        if ($this->addPolicyHeaders) {
            $config = Injector::inst()->convertServiceProperty(CSPBackend::config()->get('csp_config'));
...
```

### PR DESCRIPTION
**Pull request by phptek**

### CODE REVIEW

**Comment by Firesphere** [comment]
As CodeCov upload somehow didn't do it's job, I'm unclear what the implications for the code coverage is. Do you have any information around that?

**Comment by Firesphere** [comment]
Also, unrelated, I'm confused why it didn't show up in my notifications.

**Comment by phptek** [comment]
Do contributers need to provide something in addition to the patch itself? Otherwise, sorry. No idea atm

**Comment by Firesphere** [comment]
No, it should usually "just run", but turns out no coverage changes, so no big deal in the end :)

**Pull request merged**
